# Created with WinGet Releaser using komac v2.6.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Genivia.ugrep
PackageVersion: 7.0.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: ug.exe
- RelativeFilePath: ugrep.exe
ReleaseDate: 2024-10-26
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Genivia/ugrep/releases/download/v7.0.1/ugrep-windows-x64.zip
  InstallerSha256: EAB15C7B769DCBD99F3FC895ADE332706A80E9C7E706D3CF6206547B94CBDDEB
ManifestType: installer
ManifestVersion: 1.6.0
