# Created with WinGet Releaser using komac v2.9.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: Genivia.ugrep
PackageVersion: 7.2.0
PackageLocale: en-US
Publisher: Genivia Inc.
PublisherUrl: https://www.genivia.com/
PublisherSupportUrl: https://github.com/Genivia/ugrep/issues
Author: Robert van Engelen
PackageName: ugrep
PackageUrl: https://github.com/Genivia/ugrep
License: BSD-3-Clause
LicenseUrl: https://github.com/Genivia/ugrep/blob/HEAD/LICENSE.txt
Copyright: Copyright (c) 2023, Robert van Engelen, Genivia Inc.
CopyrightUrl: https://github.com/Genivia/ugrep/blob/master/LICENSE.txt
ShortDescription: An ultra-fast, user-friendly, and compatible grep replacement
Description: |-
  An ultra-fast, user-friendly grep replacement.
  Ugrep combines the best features of other grep, adds new things, and surpasses their search speeds.
  Includes a TUI, boolean queries (AND/OR/NOT), fuzzy search, hexdumps, searches nested archives (cpio/tar/pax/zip), compressed files (zip/gz/Z/bz2/lzma/xz/lz4/zstd), pdfs, docs, and more
Tags:
- code-search
- file-indexing
- file-search
- fuzzy-search
- grep
- hexdump
- interactive
- recursively-search
- regex
- ripgrep
- search
- silver-searcher
- tar
- tui
- unicode
- zip
ReleaseNotes: |-
  What's new?
  - new options --no-files-with-matches and --no-count #452
  - update options -i and -j when used together: -i unconditional case-insensitive matching should override -j smart-case conditional case-insensitive matching #453
  - new adoc type added to option -t or --file-type #456
  - new full support for GNU/BSD grep option -z (--null-data), such that -z is reassigned from --decompress to --null-data when ugrep is specifically copied or symlinked with the target name grep, egrep, fgrep, zgrep, zegrep, or zfgrep executable file binaries to run as replacements of GNU/BSD grep #457
  - fix older MacOS build from source compile-time error QOS_CLASS_USER_INITIATED not declared #458
  - fix a bug in ugrep v7 when matching certain case-insensitive patterns at the very end of a file at EOF when an EOL before EOF is missing (this is not a problem in versions prior to v7) #461
ReleaseNotesUrl: https://github.com/Genivia/ugrep/releases/tag/v7.2.0
ManifestType: defaultLocale
ManifestVersion: 1.9.0
