# Created with WinGet Releaser using komac v2.6.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: Genivia.ugrep
PackageVersion: 7.0.0
PackageLocale: en-US
Publisher: Genivia Inc.
PublisherUrl: https://www.genivia.com/
PublisherSupportUrl: https://github.com/Genivia/ugrep/issues
Author: Robert van Engelen
PackageName: ugrep
PackageUrl: https://github.com/Genivia/ugrep
License: BSD-3-Clause
LicenseUrl: https://github.com/Genivia/ugrep/blob/HEAD/LICENSE.txt
Copyright: Copyright (c) 2023, Robert van Engelen, Genivia Inc.
CopyrightUrl: https://github.com/Genivia/ugrep/blob/master/LICENSE.txt
ShortDescription: An ultra-fast, user-friendly, and compatible grep replacement
Description: |-
  An ultra-fast, user-friendly grep replacement.
  Ugrep combines the best features of other grep, adds new things, and surpasses their search speeds.
  Includes a TUI, boolean queries (AND/OR/NOT), fuzzy search, hexdumps, searches nested archives (cpio/tar/pax/zip), compressed files (zip/gz/Z/bz2/lzma/xz/lz4/zstd), pdfs, docs, and more
Tags:
- code-search
- file-indexing
- file-search
- fuzzy-search
- grep
- hexdump
- interactive
- recursively-search
- regex
- ripgrep
- search
- silver-searcher
- tar
- tui
- unicode
- zip
ReleaseNotes: |-
  What's new?
  - rewritten SIMD acceleration logic and the search algorithm selection decision logic to speed up pattern matching (the actual speedup depends on the type of regex patterns specified) #432
  - improved regex anchors and word boundary matching speed and support #426 and #427
  - fix option --xml pathnames with special characters, which are unlikely to occur in pathnames, but aren't strictly forbidden #430
  - updated option --hexdump with -ABC context hex lines before and after a match #428
  - the TUI now also uses the VISUAL environment variable if PAGER is not set
ReleaseNotesUrl: https://github.com/Genivia/ugrep/releases/tag/v7.0.0
ManifestType: defaultLocale
ManifestVersion: 1.6.0
